try { 
    let tulos = virheellinenMuuttuja + 1; 
  } catch (virhe) { 
    console.log("Virhe tapahtui: " + virhe.message); 
  } 
   